package ajp

/**
 * AJP command type
 */

const AJP_TYPE_DATA = 0
const AJP_TYPE_FORWARD_REQUEST = 2
const AJP_TYPE_SEND_BODY_CHUNK = 3
const AJP_TYPE_SEND_HEADERS = 4
const AJP_TYPE_END_RESPONSE = 5
const AJP_TYPE_GET_BODY_CHUNK = 6
const AJP_TYPE_SHUTDOWN = 7
const AJP_TYPE_PING = 8
const AJP_TYPE_CPING = 10
