package fcgi

const FCG_TYPE_BEGIN_REQUEST = 1
const FCG_TYPE_ABORT_REQUEST = 2
const FCG_TYPE_END_REQUEST = 3
const FCG_TYPE_PARAMS = 4
const FCG_TYPE_STDIN = 5
const FCG_TYPE_STDOUT = 6
const FCG_TYPE_STDERR = 7
const FCG_TYPE_DATA = 8
const FCG_TYPE_GETVALUES = 9
const FCG_TYPE_GETVALUESRESULT = 10
const FCG_TYPE_UNKNOWN_TYPE = 11
