package h2

const H2_TYPE_PREFACE = -1
const H2_TYPE_DATA = 0
const H2_TYPE_HEADERS = 1
const H2_TYPE_PRIORITY = 2
const H2_TYPE_RST_STREAM = 3
const H2_TYPE_SETTINGS = 4
const H2_TYPE_PUSH_PROMISE = 5
const H2_TYPE_PING = 6
const H2_TYPE_GOAWAY = 7
const H2_TYPE_WINDOW_UPDATE = 8
const H2_TYPE_CONTINUATION = 9
